name: voicehub
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - libsndfile
  - pip
  - pip:
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - soundfile==0.13.1
      - pydub==0.25.1
      - numpy==2.1.2
      - faster-whisper==1.0.3
      - ctranslate2==4.4.0
      - openai-whisper==20250625
      - coqui-tts==0.27.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - pydantic==2.10.6
      - fastapi==0.116.1
      - starlette==0.47.3
      - setuptools<81
      - wheel
      - langid==1.1.6
